version: '3.9'

services:
  # traefik:
  #   image: traefik:3.0
  #   command:
  #     #- "--log.level=DEBUG"
  #     - --api.insecure=true
  #     - --providers.docker=true
  #     - --providers.docker.exposedbydefault=false
  #     - --entrypoints.web.address=:80
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #   networks:
  #     - external
  #   ports:
  #     - 8000:80

  server:
    image: ghcr.io/chroma-core/chroma:0.3.27.dev14
    volumes:
      - index_data:/chroma/.chroma/index
    environment:
      - CHROMA_DB_IMPL=clickhouse
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_PORT=8123
    depends_on:
      - clickhouse
    networks:
      - internal
      - external
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.chroma.rule=Host(`${CHROMA_HOST}`)"
      - "traefik.http.routers.chroma.entrypoints=${CHROMA_ENTRYPOINT}"
      - "traefik.http.middlewares.oauth-verify.forwardAuth.address=${CHROMA_OAUTH_VERIFY_URL}"
      - "traefik.http.middlewares.oauth-verify.forwardAuth.trustForwardHeader=true"
      - "traefik.http.routers.chroma.middlewares=oauth-verify@docker"

  clickhouse:
    build:
      context: .
      dockerfile: Dockerfile.clickhouse
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - CLICKHOUSE_TCP_PORT=9000
      - CLICKHOUSE_HTTP_PORT=8123
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - clickhouse_logs:/var/log/clickhouse-server
      - backups:/backups
      # - ${PWD}/config/backup_disk.xml:/etc/clickhouse-server/config.d/backup_disk.xml # TODO
      # - ${PWD}/config/chroma_users.xml:/etc/clickhouse-server/users.d/chroma.xml # TODO
    networks:
      - internal

networks:
  internal:
    driver: bridge
  external:
    external: true
    name: ${CHROMA_NETWORK}

volumes:
  clickhouse_data:
    driver: local
  clickhouse_logs:
    driver: local
  index_data:
    driver: local
  backups:
    driver: local
